version: '3.8'

services:
  origin:
    build:
      context: ./origin-site
    container_name: origin
    networks:
      - cdn-net

  mcache:
    build:
      context: ./mcache
    container_name: mcache
    depends_on:
      - origin
    networks:
      - cdn-net

  edge:
    build:
      context: ./edge
    container_name: edge
    ports:
      - "8082:80"
    depends_on:
      - mcache
    networks:
      - cdn-net

networks:
  cdn-net:
    driver: bridge
