apiVersion: v1
kind: Service
metadata:
  name: origin
  labels:
    app: origin
spec:
  selector:
    app: origin
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 80  # container port
      nodePort: 30081
  type: NodePort     # internal-only
