apiVersion: v1
kind: Service
metadata:
  name: edge
  labels:
    app: edge
spec:
  selector:
    app: edge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP        # exposes edge outside cluster
