apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-edge
  labels:
    app: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
        - name: edge
          image: ismetss/two-layer-cdn-edge
          imagePullPolicy: Always
          ports:
            - containerPort: 80
