apiVersion: v1
kind: Service
metadata:
  name: edge
  labels:
    app: edge
spec:
  selector:
    app: edge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # you can change this if you want a different port
  type: NodePort        # exposes edge outside cluster
