{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: {{ $svc.type }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
      name: http
      {{- if eq $svc.type "NodePort" }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
---
{{- end }}
